### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function _()

### ISSUE THREAD

**Issue by BaseMax** [poweradmin/poweradmin#389]
**OS:** FreeBSD 12-2

```
# uname -a
FreeBSD max 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64
```
------

Fatal error: Uncaught Error: Call to undefined function _() in /usr/local/www/nginx-dist/powerdns/inc/error.inc.php:25

### Nginx/webserver at `site.com/powerdns/`

```
Fatal error: Uncaught Error: Call to undefined function _() in /usr/local/www/nginx-dist/powerdns/inc/error.inc.php:25 Stack trace: #0 /usr/local/www/nginx-dist/powerdns/inc/toolkit.inc.php(39): require_once() #1 /usr/local/www/nginx-dist/powerdns/index.php(32): require_once('/usr/local/www/...') #2 {main} thrown in /usr/local/www/nginx-dist/powerdns/inc/error.inc.php on line 25
```

### CLI
```
root@max:/usr/local/www/nginx/powerdns # ls
.gitignore			addons				delete_zone_templ_record.php	edit_user.php			list_zones.php
LICENSE				bulk_registration.php		dnssec.php			edit_zone_templ.php		locale
README.md			change_password.php		dnssec_add_key.php		edit_zone_templ_record.php	migrations
add_perm_templ.php		composer.json			dnssec_delete_key.php		favicon.ico			phpdoc.dist.xml
add_record.php			delete_domain.php		dnssec_ds_dnskey.php		images				robots.txt
add_supermaster.php		delete_domains.php		dnssec_edit_key.php		inc				search.php
add_user.php			delete_perm_templ.php		dynamic_update.php		index.php			sql
add_zone_master.php		delete_record.php		edit.php			install				style
add_zone_slave.php		delete_supermaster.php		edit_comment.php		list_perm_templ.php		users.php
add_zone_templ.php		delete_user.php			edit_perm_templ.php		list_supermasters.php		vendor
add_zone_templ_record.php	delete_zone_templ.php		edit_record.php			list_zone_templ.php
root@max:/usr/local/www/nginx/powerdns # php index.php 

Fatal error: Uncaught Error: Call to undefined function _() in /usr/local/www/nginx-dist/powerdns/inc/error.inc.php:25
Stack trace:
#0 /usr/local/www/nginx-dist/powerdns/inc/toolkit.inc.php(39): require_once()
#1 /usr/local/www/nginx-dist/powerdns/index.php(32): require_once('/usr/local/www/...')
#2 {main}
  thrown in /usr/local/www/nginx-dist/powerdns/inc/error.inc.php on line 25
```

**Comment by BaseMax** [comment]
Solved by installing `gettext`.

FreeBSD:
```
pkg install gettext
pkg install php80-gettext
```
