### ISSUE TITLE
edit_record function has an extraneous comma before where clause

### ISSUE THREAD

**Issue by robo-gaggle** [poweradmin/poweradmin#399]
At least for percona mysql server.

```
[23-Feb-2021 18:44:38 UTC] [* SQL ERROR MESSAGE FOLLOWS:
#0 /var/www/html/poweradmin/inc/PDOCommon.class.php(160): PDO->query('UPDATE records\n...')
#1 /var/www/html/poweradmin/inc/PDOLayer.php(133): PDOCommon->query('UPDATE records\n...')
#2 /var/www/html/poweradmin/inc/record.inc.php(399): PDOLayer->query('UPDATE records\n...')
#3 /var/www/html/poweradmin/edit.php(67): edit_record(Array)
#4 {main}
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id='4'' at line 7
Full SQL Statement:UPDATE records
				SET name='bar.ribeye.net',
				type='A',
				content='2.2.2.3',
				ttl='3600',
				prio='0',
				WHERE id='4'
*]
```

```
git diff inc/record.inc.php
diff --git a/inc/record.inc.php b/inc/record.inc.php
index 6553509..16d008d 100644
--- a/inc/record.inc.php
+++ b/inc/record.inc.php
@@ -394,7 +394,7 @@ function edit_record($record) {
                                type=" . $db->quote($record['type'], 'text') . ",
                                content=" . $db->quote($record['content'], 'text') . ",
                                ttl=" . $db->quote($record['ttl'], 'integer') . ",
-                               prio=" . $db->quote($record['prio'], 'integer') . ",
+                               prio=" . $db->quote($record['prio'], 'integer') . "
                                WHERE id=" . $db->quote($record['rid'], 'integer');
             $result = $db->query($query);
             if (PEAR::isError($result)) {
```

**Comment by edmondas** [comment]
@robo-gaggle thanks for contribution.

**Comment by robo-gaggle** [comment]
Thank you @edmondas! I wouldn't mind at all if this issue was deleted/redacted, in fact I'd prefer it... I'll do a PR next time!
