### ISSUE TITLE
Integrity constraint violation at installation

### ISSUE THREAD

**Issue by julian70400** [poweradmin/poweradmin#537]
Hello, 

Currently installing PowerADMIN after using for years PowerDNS-Manager.

PowerDNS Authoritative Server 4.7.3
Debian 12.2 - PHP 8.2

Got this error at Step 4 installation : 

2023/12/11 12:32:20 [error] 141780#141780: *3342 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails in /usr/share/nginx/html/gestion-domaines.mysite.org/inc/PDOLayer.php:210
Stack trace:
#0 /usr/share/nginx/html/gestion-domaines.mysite.org/inc/PDOLayer.php(210): PDO->exec()
#1 /usr/share/nginx/html/gestion-domaines.mysite.org/install/helpers/database_helpers.php(32): PDOLayer->dropTable()
#2 /usr/share/nginx/html/gestion-domaines.mysite.org/install/helpers/install_helpers.php(79): updateDatabase()
#3 /usr/share/nginx/html/gestion-domaines.mysite.org/install/index.php(60): step4()
#4 {main}
  thrown in /usr/share/nginx/html/gestion-domaines.mysite.org/inc/PDOLayer.php on line 210" while reading response header from upstream, client: 45.80.8.36, server: gestion-domaines.mysite.org, request: "POST /install/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "gestion-domaines.mysite.org", referrer: "https://gestion-domaines.mysite.org/install/"

![image](https://github.com/poweradmin/poweradmin/assets/43498802/aa8b883a-4413-4f37-aa68-49929eabaf70)
![image](https://github.com/poweradmin/poweradmin/assets/43498802/8ab9928b-a1af-44f1-bb9b-26256cb9b99f)

Can anybody provide some help, please ? THanks

**Comment by julian70400** [comment]
Ok, if you are coming from  PowerDNS-Manager, installation of Poweradmin will fail if you do not drop manually somes tables (permissions, users, ...) because foreign keys.
