### ISSUE TITLE
Updating zones from template page doe not work with sqlite backend

### ISSUE THREAD

**Issue by FabienZouaoui** [poweradmin/poweradmin#538]
Hello,

When I try to update zones from template page, I get the following error:
```
2023/12/16 17:00:42 [error] 3102403#3102403: *763774 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 near "r": syntax error in /usr/local/poweradmin-3.6.0/lib/DnsRecord.php:1630
Stack trace:
#0 /usr/local/poweradmin-3.6.0/lib/DnsRecord.php(1630): PDO->prepare()
#1 /usr/local/poweradmin-3.6.0/edit_zone_templ.php(153): Poweradmin\DnsRecord::update_zone_records()
#2 /usr/local/poweradmin-3.6.0/edit_zone_templ.php(94): EditZoneTemplController->updateZoneRecords()
#3 /usr/local/poweradmin-3.6.0/edit_zone_templ.php(67): EditZoneTemplController->updateZoneTemplate()
#4 /usr/local/poweradmin-3.6.0/edit_zone_templ.php(160): EditZoneTemplController->run()
#5 {main} 
```

it seems that the following query (line 1628 in DnsRecord.php) is not valid with sqlite3:
`"DELETE r, rzt FROM records r LEFT JOIN records_zone_templ rzt ON r.id = rzt.record_id WHERE rzt.domain_id = :zone_id AND rzt.zone_templ_id = :zone_template_id"`

**Comment by edmondas** [comment]
Thank you for reporting this issue. It has been fixed and will be released with the next version.
