### ISSUE TITLE
installer stuck in step4 with PHP fatal error.

### ISSUE THREAD

**Issue by gav-de-2** [poweradmin/poweradmin#607]
Hello everybody,
I need help.
When I run the installer, I only get to step 4.
there it says "Updating database... " but it is not getting any further.
My php error log says this:
[Mon Nov 18 14:54:16.664483 2024] [php:error] [pid 108367] [client x.x.x.x:40518] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails in /var/www/html/poweradmin-3.8.1/lib/PDOLayer.php:222\nStack trace:\n#0 /var/www/html/poweradmin-3.8.1/lib/PDOLayer.php(222): PDO->exec()\n#1 /var/www/html/poweradmin-3.8.1/install/helpers/database_helpers.php(33): Poweradmin\\PDOLayer->dropTable()\n#2 /var/www/html/poweradmin-3.8.1/install/helpers/install_helpers.php(90): updateDatabase()\n#3 /var/www/html/poweradmin-3.8.1/install/index.php(59): step4()\n#4 {main}\n  thrown in /var/www/html/poweradmin-3.8.1/lib/PDOLayer.php on line 222, referer: https://poweradmin.x.x/install/

Regards,
Gerald

**Comment by gav-de-2** [comment]
I think I found out what's wrong: after manually separating the pdns tables from the poweradmin tables in two separate databases, it worked. Beforehand, the installer was not able to create the table "user" in the pdns database, because it already existed, due to the fact that we are using pdnsmanager. (Which has a similar structure and a user table of its own in the pdns database.)

**Comment by gav-de-2** [comment]
I think this issue can be closed.  If my presumption is correct, then it's not a real bug.

**Comment by edmondas** [comment]
Maybe we should have some kind of installation checks in place for such cases.?

**Comment by gav-de-2** [comment]
That would be so wonderful!
And probably: separation of pdns-dta and poweradmin-data in two databases is a good decision.

**Comment by bessone** [comment]
From what i understand the separation has been implemented but it is not in the installer. i can't find references in the config to set the two databases, is there some detail in the code to look for?

**Comment by edmondas** [comment]
@bessone

**Comment by edmondas** [comment]
Closing this ticket as the original issue is not valid. However, I've created a new ticket (#633) to track the installer improvements that were discussed here.
