### ISSUE TITLE
Button 'Save changes' throws PHP fatal error in last commit

### ISSUE THREAD

**Issue by michielvisser** [poweradmin/poweradmin#617]
I've checked out the latest commit 63bdaf7 to check the last improvements made for #581 and changed the settings to get the button for Save Changes to the top which works really well. 

I can add, edit and delete single records fine, no issues there. However, when I use the Save Changes button a fatal PHP error is thrown and the form update is not working:

```
[30-Dec-2024 11:01:37 Europe/Amsterdam] PHP Fatal error:  Uncaught TypeError: Poweradmin\Application\Service\RecordCommentService::updateComment(): Argument #6 ($comment) must be of type string, null given, called in /opt/poweradmin/master/lib/Application/Controller/EditController.php on line 350 and defined in /opt/poweradmin/master/lib/Application/Service/RecordCommentService.php:62
Stack trace:
#0 /opt/poweradmin/master/lib/Application/Controller/EditController.php(350): Poweradmin\Application\Service\RecordCommentService->updateComment()
#1 /opt/poweradmin/master/lib/Application/Controller/EditController.php(92): Poweradmin\Application\Controller\EditController->saveRecords()
#2 /opt/poweradmin/master/lib/Application/Routing/BasicRouter.php(108): Poweradmin\Application\Controller\EditController->run()
#3 /opt/poweradmin/master/index.php(46): Poweradmin\Application\Routing\BasicRouter->process()
#4 {main}
  thrown in /opt/poweradmin/master/lib/Application/Service/RecordCommentService.php on line 62
```

I have no comment on the zone so that field is empty. I've tried with a comment present before trying to save changes but this gives the same result. 

OS: CentOS 9 Stream
PHP: 8.2.27

**Comment by edmondas** [comment]
Thanks, good catch! Somehow I missed that while testing. It should be fixed now.
